# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "jizhangji"
	LogPath     = "./log/jizhangji/server"

# Logger.
[logger]
    Path        = "./log/jizhangji"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# Database.
[database]
    link  = "mysql:root:A123456@tcp(localhost:3306)/jizhangji"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/jizhangji/sql"
        Level  = "all"
        Stdout = true

#[jwt]
#    #过期时间
#    timeout = 3600
#    #token分割符
#    refresh = 1800
#    #安全密钥
#    encryptKey = "jizhangji"

[ledger]
    # 一个用户最多拥有多少个账本
    max     =   10

# gtoken配置文件
[gtoken]
    # 缓存模式 1 gcache 2 gredis
    cache-mode = 2
    # 是否支持多端登录
    multi-login = true


# Redis数据库配置
[redis]
    default = "localhost:6379,0,123456?idleTimeout=600"
    cache   = "localhost:6379,1,123456?idleTimeout=600"